#!/usr/bin/python

import os
import sys
import hooking

'''
Remove CPU model hook
=====================


This hook removes CPU model information from
libvirt XML otherwise networking in Solaris
want work.

          !!! Important !!!
*********************************************
Make sure you use the same CPU family in your
cluster and keep in mind that Solaris want
work on AMD CPUs.
*********************************************


Add vdsm hook to oVirt engine:

# engine-config -s UserDefinedVMProperties=remove_cpu_model=^(true|false)$' --cver=3.4
# service ovirt-engine restart

Remove CPU model for a specific vm (in oVirt webadmin):

In the VM configuration window, open the custom
properites tab and add remove_cpu_model=true for
removing of CPU model information.
'''


if hooking.tobool(os.environ.get('remove_cpu_model')):
	domxml = hooking.read_domxml()

	# cpu fixes
	cpu = domxml.getElementsByTagName('cpu')[0]
	cpu.removeAttribute('match')
	cpumodel = cpu.getElementsByTagName('model')[0]
	cpumodel.parentNode.removeChild(cpumodel)
	
	hooking.write_domxml(domxml)

sys.exit(0)
